# Generated by Django 5.1.7 on 2025-03-15 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Election Candidates'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Election Positions'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Election Votes'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Voter List'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.RemoveField(
            model_name='election',
            name='electco',
        ),
        migrations.RemoveField(
            model_name='election',
            name='voteYN',
        ),
        migrations.RemoveField(
            model_name='position',
            name='voteYN',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='title',
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='clientapp.position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='vote_type',
            field=models.CharField(choices=[('single', 'Single Candidate Selection'), ('multiple', 'Multiple Candidate Selection'), ('yes_no', 'Yes/No Vote')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.position'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='max_vote',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='election',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending Approval')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='instructions',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='max_vote',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YesNoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_yn', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='position/YesNoOption/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_ynoption', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_options', to='clientapp.position')),
            ],
            options={
                'verbose_name_plural': 'Election Position YesNoOption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.AddConstraint(
            model_name='yesnooption',
            constraint=models.UniqueConstraint(fields=('position', 'vote_yn'), name='unique_yes_no_option'),
        ),
    ]
