"""
Django settings for synergyevote project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%5^crv50bvma&53y*yha9+#@3yu^z+i@h10+2nu6@!g_(gazba'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['synergyevote.net', '.synergyevote.net', '127.0.0.1', 'localhost']

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']
ALLOWED_HOSTS = []
# CSRF_TRUSTED_ORIGINS = [ 'https://*' ]
# Application definition

SHARED_APPS = [
    'django_tenants',
    'govote',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',  # Swagger Documentation
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
]

TENANT_APPS = [
    "clientapp",  # Your tenant-specific app
]

INSTALLED_APPS= SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.TenantMainMiddleware',  # Must be first!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'synergyevote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'synergyevote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#using pg Adming localhost
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',  # Required for django-tenants
        'NAME': 'db_synergy_govote',
        'USER': 'postgres',
        'PASSWORD': 'sajetAdmin',
        'HOST': 'localhost',  # Or your database host
        'PORT': 5432,  # Default PostgreSQL port
    }
}

#using docker container 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django_tenants.postgresql_backend',
#         'NAME': 'db_synergy_govote',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',  # Match with Docker
#         'HOST': 'locahost',  # Use the container name, NOT 'localhost'
#         'PORT': 5432,
#     }
# }

DATABASE_ROUTERS = [
    'django_tenants.routers.TenantSyncRouter',  # Correct syntax
]
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Add this to specify where collected static files will be placed
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Ensure BASE_DIR is set in your settings

# Optionally, if you have custom static files (CSS, JS, images), ensure this is set
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # This should be the path where your custom static files are stored
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

TENANT_HOSTNAME = "localhost"  # The default domain for the public schema

TENANT_MODEL = "govote.Client"
TENANT_DOMAIN_MODEL = "govote.Domain"

TENANT_PUBLIC_SCHEMA = "govote.urls"  # Ensure this is set
